### ISSUE TITLE
RTS_Data/FormattedData/pandapower/source_data_to_pp.py Query

### ISSUE THREAD

**Issue by Misbahrani** [GridMod/RTS-GMLC#108]
Hello
I have run this file and exported the results to excel, in the parameters tab, the OPF converged is false, so it means that OPF wasn't converged???
![image](https://user-images.githubusercontent.com/52325843/61405323-f5267100-a8f2-11e9-99fd-13c10648e876.png)

**Comment by FlorianShepherd** [comment]
@Misbahrani Have you tried to run an opf or just assume that it doesn't work because it says in the excel file? 
Please try:

```
import pandapower as pp
net = pp.from_excel("your_rts_path.xlsx")
pp.runopp(net)
print(net.res_bus)
```
Do you see any results?
