### ISSUE TITLE
Forecast data

### ISSUE THREAD

**Issue by Baldick** [GridMod/RTS-GMLC#11]
Does the dataset include forecast data as well as the operation data?

Eg, if I wanted to model day ahead operations, I would want to use a renewable forecast,

and then model real-time operations to dispatch to the actual renewable production.

Thanks!
Ross

**Comment by claytonpbarrows** [comment]
Yes.
 - The file pointers for the Day-Ahead forecasted generation profiles are in the [vg_gens_DA.csv](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/vg_gens_DA.csv) and the profiles themselves are in the [timeseries_data_files](https://github.com/GridMod/RTS-GMLC/tree/master/RTS_Data/timeseries_data_files/wind_pv_rtpv) folder. The DA profiles are intended to represent the best available forecast 24-hours ahead of time.
   - The hourly Day-Ahead solar and wind profiles are a subset of the profiles produced for the [WWSIS-2 study](http://www.nrel.gov/docs/fy13osti/55588.pdf) and were generated using a numerical weather prediction model. 
 - The file pointers for the Real-Time generation profiles are in the [vg_gens_RT.csv](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/vg_gens_RT.csv) and the profiles themselves are in the [timeseries_data_files](https://github.com/GridMod/RTS-GMLC/tree/master/RTS_Data/timeseries_data_files/wind_pv_rtpv) folder. The RT profiles are intended to represent *actual* generation profiles.
   - The 5-minute Real-Time wind profiles are also created using the same numerical weather prediction model as the DA profiles. 
   - The 5-minute Real-Time solar PV (utility-scale, and rooftop) profiles are based on satellite-derived irradiance data.  Additionally, an [algorithm](http://www.nrel.gov/docs/fy13osti/56204.pdf) is applied to introduce synthetic 5-minute variability into the natively hourly resolution data. 

More information is available in the technical publications of the  [WWSIS-2 study](http://www.nrel.gov/docs/fy13osti/55588.pdf) and [LCGS](http://www.nrel.gov/docs/fy16osti/64884.pdf) from which the data provided here is sampled.
