### ISSUE TITLE
Transmission lines' data

### ISSUE THREAD

**Issue by amnsrhn** [GridMod/RTS-GMLC#118]
Hello every one, 

I am new to bulk power system reliability analysis, so I would like to know the following points:

1. In transmission lines' data, what are the difference between **Outage rate**  and **FOR** in file of generators.
2. Are **Mean outage duration** and **MTTR** same or different?

Thank you

**Comment by oaansari** [comment]
Hi, 

1. The outage rate represents the number of failures/year; it is not a probability.  
FOR (Forced outage rate) represents the probability of the failure of the generating unit. The term "rate" in FOR can be misleading but it's used for historical purposes. 

2.  Yes, mean outage duration and MTTR are the same.

**Comment by amnsrhn** [comment]
Thank you so much

**Comment by amnsrhn** [comment]
Dear Osama Ansari,

Do you the differences between **Perm OutRate** and  **Tran OutRate**?

Thank you so much
