### ISSUE TITLE
the "start heat warm" of 121_Nuclear_1 

### ISSUE THREAD

**Issue by nnhjy** [GridMod/RTS-GMLC#119]
I found the value 0. It seems weird as being between "start heat cold" and "start heat hot".\
https://eu-prod.asyncgw.teams.microsoft.com/v1/objects/0-weu-d6-ab88f564a952de7e847bf165d8cac627/views/imgo

**Comment by claytonpbarrows** [comment]
@nnhjy, the startup data for the nuclear unit is not really valid. The startup times from cold and hot are all 9999 (meaning invalid data *note that I hate this convention*). Also, the startup heat values should be interpreted as "heat required to start from x state", where x is cold, and hot. 

As @danielolsen mentioned in an email, which was not properly addressed in #93, the warm start time data is mis labeled here. According to [table 10](https://labs.ece.uw.edu/pstca/rts/rts96/Table-10.txt) in the RTS-96 dataset, warm start times refer to the time it takes to transition from hot to cold after a shutdown.  So, looking through my records, I believe that the creation of the "start heat warm" column was erroneous and it should be removed. In addition, the label applied to the "start time warm" column should be changed to "The transition time between hot and cold statuses after a shutdown".

**Comment by nnhjy** [comment]
It's been well addressed. Thank you @claytonpbarrows

**Comment by nnhjy** [comment]
Perhaps we should wait @danielolsen to reply.

**Comment by danielolsen** [comment]
@claytonpbarrows's recollection of our conversation (from two years ago!) tracks with mine, and I support the changes that he proposes.

**Comment by claytonpbarrows** [comment]
@danielolsen I had help from the gods of searchable email.
