### ISSUE TITLE
If I want to .dyr file in PSS/E, can  you help me? Please!

### ISSUE THREAD

**Issue by learningelectric** [GridMod/RTS-GMLC#135]

**Comment by claytonpbarrows** [comment]
Hi @learningelectric, 
I'm sorry, I don't follow your question. Do you want to add a .dyr file to the repository? Or, are you looking for a .dyr file? If the case is the former, yes I can help add one if you have one to contribute. However, if the case is the latter, unfortunately I do not know of any .dyr files for the RTS system.
