### ISSUE TITLE
How to get nodal load, there is no proportion of the total regional load consumed at each bus defined in the [`bus.csv`]

### ISSUE THREAD

**Issue by ylic204** [GridMod/RTS-GMLC#137]
Hello, 

I see that the documentation for # Timeseries Data Files mentions "To get nodal load, multiply the regional load timeseries by the proportion of the total regional load consumed at each bus defined in the [`bus.csv`](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/SourceData/bus.csv)". But I don't find the corresponding scale value in bus.csv, which only has the following values.

| Bus ID       | Numeric Bus ID                    |
| Bus Name     | Bus name from RTS-96    |
| BaseKV       | Bus voltage rating              |
| Bus Type     | Bus control type                 |
| MW Load      | Real power demand         |
| MVAR Load    | Reactive power demand  |
| V Mag        | Voltage magnitude setpoint |
| V Angle      | Voltage angle setpoint in degrees |
| MW Shunt G   | Shunt conductance           |
| MVAR Shunt B | Shunt susceptance          |
| Area         | Area membership                   |
| Sub Area     | Sub area membership          |
| Zone         | Zone membership                   |
| lat          | Bus latitude location             |
| lng          | Bus longitude location            |

**Comment by claytonpbarrows** [comment]
You can determine the load participation factors by summing the `MW Load` value for all loads in each area, then dividing the `MW Load` value for each load by the total area load.
