### ISSUE TITLE
Location of buses on wind/solar resource map

### ISSUE THREAD

**Issue by jahanbani** [GridMod/RTS-GMLC#138]
Thank you for providing a well-organized dataset. I want to use this dataset for long-term planning purposes; however, one missing data (or maybe I couldn't find it) is the location of buses on the map of wind/solar resources. Could you share this set of data as well?
Thank you

**Comment by claytonpbarrows** [comment]
Oh, I see. Unfortunately, I don't have that data. Someday, I'd like to update the wind and solar datasets to use a more complete resource potential source data (e.g. NSRDB or WindToolkit), but for now the wind and solar data are sampled from the data assembled for the WWSIS phase 2 study, so I only have the representative sites to draw from, not the complete resource data set.

**Comment by jahanbani** [comment]
Thank you Clayton. 
I can see the time series data for regional load, but are there any time series data for the load of each bus? If not, is there a fraction matrix that can map regional load to bus load? my goal is to have the time-series load data per bus.
Thank you,
Ali

**Comment by claytonpbarrows** [comment]
You need to derive the load distribution factors based on the MW load column in the bus.csv table. You can then multiply the distribution factors by the the time series to get bus specific time series. see #54
