### ISSUE TITLE
Question about hydro and solar data

### ISSUE THREAD

**Issue by ikrad** [GridMod/RTS-GMLC#17]
1.	I see there is only 1 hydro profile per region. Does that mean each hydro generator has that exact same schedule or is that schedule divided amongst all the hydro generators in a region.

2.	What’s the difference between “pv” and “rtpv”?

**Comment by claytonpbarrows** [comment]
"PV" is utility scale PV 
"RTPV" is rooftop PV

**Comment by claytonpbarrows** [comment]
Each hydro unit in each region uses the same hydro profile.
