### ISSUE TITLE
vg generators and hydro

### ISSUE THREAD

**Issue by kibaekkim** [GridMod/RTS-GMLC#23]
Are vg generators and hydro (defined in `vg_gens_DA.csv` and `hydro_profiles.csv`, respectively) considered in addition to the generation capacity defined in `RTS.m`?

**Comment by oconnellm** [comment]
VG generators are added to the gen capacity defined in the `RTS.m` file. So yes for those. 

Hydro generation capacity is already defined in the `RTS.m` file, but the fixed generation profiles are added through the `hydro_profiles.csv` (which link to the timeseries_data_files/hydro/region* files). So no for hydro.

**Comment by kibaekkim** [comment]
Thanks!

**Comment by kibaekkim** [comment]
What should be the IDs in `RTS.m` for hydros?

**Comment by claytonpbarrows** [comment]
see reorganization branch and #44

**Comment by claytonpbarrows** [comment]
0cfa67f3e3b5d715c138bd8df4294f6555e91ab9 closes
