### ISSUE TITLE
Generation dispatch output data/unit commitment data

### ISSUE THREAD

**Issue by krishnakanaparthi** [GridMod/RTS-GMLC#28]
Does the dataset also provide generation dispatch output for the whole year based on the published hourly load profiles? We are doing the transmission dispatch and want to understand how the power flows through existing transmission through the year.

For this, I was wondering if the generation dispatch output/ unit commitment data for the RTS model is already available. Any information in this regard without going through PLEXOS or other unit commitment formulation would be much appreciated.

Thanks!
Krishna.

**Comment by claytonpbarrows** [comment]
We have solved an annual UC/ED for the hourly and 5-minute models using PLEXOS. So, we could provide the dispatch at either resolution that results from solving the PLEXOS formulation.

**Comment by kibaekkim** [comment]
@claytonpbarrows Is there a documentation for the PLEXOS formulation?

**Comment by krishnakanaparthi** [comment]
At this moment, we need hourly information of the dispatch. If the 5-minute resolution dispatch could also be provided at the same time, we can use it at a later stage when needed.

Thanks,
Krishna.

**Comment by claytonpbarrows** [comment]
@kibaekkim, not really. The PLEXOS documentation gives good detail on how each option is formulated, but closest thing I can get to a complete formulation is *.MPS files that describe each problem step.

**Comment by claytonpbarrows** [comment]
will add LMP values to address #35
