### ISSUE TITLE
Same LMP values at all buses for DCOPF

### ISSUE THREAD

**Issue by krishnakanaparthi** [GridMod/RTS-GMLC#31]
When DC OPF is run on the RTS data (using the RTS.m file), the LMP values obtained at all the buses are the same. But AC OPF gives different LMPs at the buses. This might not be an issue but an observation regarding the data set.

**Comment by claytonpbarrows** [comment]
are you using MATPOWER?

**Comment by krishnakanaparthi** [comment]
Yes, I used MATPOWER with GLPK solver. Also was the same with the initial formulation in Python with GLPK implementation.

**Comment by claytonpbarrows** [comment]
With all generators committed, the DCOPF doesn't have any binding transmission constraints, therefore the LMP values will all be the same. If you can optimize the unit commitment, you will find periods where transmission constraints are binding and LMP values are not uniform.

**Comment by krishnakanaparthi** [comment]
Thank you, I agree. The unit commitment information available should address this issue.
