### ISSUE TITLE
gen costs

### ISSUE THREAD

**Issue by rafcastro99** [GridMod/RTS-GMLC#37]
I'm trying to figure out how to map cost to generators. The file RTS.m contains a section mpc.gencost, but the data in this section doesn't appear to include an identifier that can be tied to generators. Also found that the file gen_params.csv contains fuel info, but only for a small subset of the generators. Can you help? Thanks!

**Comment by ArgonneTodd** [comment]
My understanding is that the gen_params file contains parameters for 11 generic unit types. The gen_id file provides the full list of 96 units, which are each assigned one of the 11 unit types. So there is fuel info for each unit, you just have to map between the two files.

However, it seems that more unit parameters are needed. I'm not sure how to determine variable and fixed O&M costs from the gen_params.csv file. I also don't see heat rates or efficiencies that could be used to translate fuel costs to generation costs. 

More detailed column header descriptions would be helpful as well (I see that this is on the todo list)

**Comment by rafcastro99** [comment]
Thanks ArgonneTodd! I now understand how to map the 11 types in gen_params to the units in gen_id. Any  ideas if the cost data in section mpc.gencost serves any purpose and, if so, how to map it to generators?

**Comment by oconnellm** [comment]
The data in section mpc.gencost of the RTS.m file gives start and shutdown costs ($), load point (MW) and the corresponding heat rate (Btu/kWh). There are three load points / heat rates for each generator.

**Comment by claytonpbarrows** [comment]
correction... the Price-Quantity pairs in the gencost matrix in the RTS.m has units of $/hr for Price and MW for quantity.

**Comment by rafcastro99** [comment]
Thanks oconnellm. My difficulty is mapping each row in mpc.gencost to each generator... There doesn't appear to be a key in mpc.gencost to map to mpc.gen. Having said that, it just dawned on me that perhaps the mapping is implicitly done using the order of the records, ie the first record in mpc.gencost maps to the first record in mpc.gen, the second record in mpc.gencost maps to the second record in mpc.gen, and so on until the 96th record. Is that right?

**Comment by rafcastro99** [comment]
@claytonpbarrows did you mean to say that the price-quantity pairs in the gencost matrix has units of $/MWhr for price and MW for quantity?

**Comment by claytonpbarrows** [comment]
No, I actually think that it is $/hr and MW. see the [CASEFORMAT](http://www.pserc.cornell.edu/matpower/docs/ref/matpower5.0/caseformat.html) for matpower. 

Also, yes the gencost matrix is implicitly indexed with the same order as the generator matrix in RTS.m

**Comment by rafcastro99** [comment]
Thanks to all for the responses.
