### ISSUE TITLE
Unit Expansion Analysis

### ISSUE THREAD

**Issue by ArgonneTodd** [GridMod/RTS-GMLC#38]
From the perspective of unit expansion analysis, could you clarify whether the gen_id file defines a) the set of existing units in the system or b) the set of candidate units in the system. Thanks!

**Comment by claytonpbarrows** [comment]
The [gen_id.csv](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/gen_id.csv) file has all of the existing units in the system, except the wind and solar units that were inserted. We should add the units to the RTS.m file. see #40
