### ISSUE TITLE
info on VG data

### ISSUE THREAD

**Issue by rafcastro99** [GridMod/RTS-GMLC#42]
a few questions:
- what's the unit of measure for the values in the DA_wind and RT_wind files?
- what's the unit of measure for the values in the DA_pv and RT_pv files?
- what's the unit of measure for the values in the DA_rtpv and RT_rtpv files?
- is there any document that contains the answer to the unit of measure questions above? (if not, I can volunteer to create one as I get questions answered)
- for the wind generator 309_wind, is it correct to assume that 309 is the bus the generator is connected to?
Thanks

**Comment by claytonpbarrows** [comment]
- the unit of measure on all RE profiles in capacity factor, or percentage of rated capacity.
- yes, the 309_wind is connected to bus 309.

**Comment by rafcastro99** [comment]
Thanks @claytonpbarrows
