### ISSUE TITLE
reorganize RTS_Data

### ISSUE THREAD

**Issue by claytonpbarrows** [GridMod/RTS-GMLC#44]
Reorganize RTS_Data to house the SourceData in accessible  CSV files instead of MATPOWER format. 

Provide FormattedData folder with formatting specific to different PCM tools.

**Comment by ikrad** [comment]
Are you planning on removing the MATPOWER formatted file or add the csv files to it?

**Comment by claytonpbarrows** [comment]
if you look in the [reorganize branch](https://github.com/GridMod/RTS-GMLC/tree/reorganize) you can see the reorganized structure. We plan on having a SourceData folder with CSV files that are accessable but not formatted for any specific tool. Additionally, for specific tool applications there is a FormattedData folder with datasets that reflect the SourceData but have been formatted for easy application (MATPOWER, and PLEXOS... for now)

**Comment by claytonpbarrows** [comment]
0cfa67f3e3b5d715c138bd8df4294f6555e91ab9 closes
