### ISSUE TITLE
Reactive load

### ISSUE THREAD

**Issue by ikrad** [GridMod/RTS-GMLC#48]
Is there any information regarding reactive load?

**Comment by claytonpbarrows** [comment]
Yes, there is a peak reactive load value for each bus in the MATPOWER file, and also in the reorganize branch (see #44) in the [bus.csv](https://github.com/GridMod/RTS-GMLC/blob/reorganize/RTS_Data/SourceData/bus.csv).

We don't have any info on reactive load profiles.
