### ISSUE TITLE
Fuel prices

### ISSUE THREAD

**Issue by rafcastro99** [GridMod/RTS-GMLC#50]
Please clarify the UOM for the values in fuel_prices.csv. Thanks

**Comment by claytonpbarrows** [comment]
please use the [reorganize branch](https://github.com/GridMod/RTS-GMLC/tree/reorganize)
I'm trying to get to a merge point ASAP to make the changes official.

In particular see the [gen.csv](https://github.com/GridMod/RTS-GMLC/blob/reorganize/RTS_Data/SourceData/gen.csv) which has a column for fuel prices for each generator
