### ISSUE TITLE
Load distribution

### ISSUE THREAD

**Issue by rafcastro99** [GridMod/RTS-GMLC#54]
Please clarify how area load is distributed to individual buses. Thanks

**Comment by claytonpbarrows** [comment]
The `MW Load` column in [bus.csv](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/SourceData/bus.csv) defines the peak load value at each bus. That value is used to define the static load distribution factors by dividing the `MW Load` value by the sum of `MW Load` for each `Area`.
