### ISSUE TITLE
CSV error when opening branch.csv

### ISSUE THREAD

**Issue by jennielu92** [GridMod/RTS-GMLC#57]
@claytonpbarrows @kdheepak 
Excel throws a weird error when you try to open RTS_Data\SourceData\branch.csv. This is a known issue in Excel when a CSV starts with "ID". For further reading, see here: http://www.alunr.com/excel-csv-import-returns-an-sylk-file-format-error/

Possible solutions include: renaming the first column ('SID' or 'id' work fine, for example), or put a different column first. We did not attempt to make any changes for fear of causing downstream errors.

**Comment by claytonpbarrows** [comment]
change column name to `UID`
