### ISSUE TITLE
NoLoadCost and Warm Start MBTU

### ISSUE THREAD

**Issue by rafcastro99** [GridMod/RTS-GMLC#58]
Couple of questions:
- The model includes MBTU for Cold and Hot starts but not for Warm. Is a value for Warm available?
- is the value for No Load Cost (or MBTU) available in the model?
Thanks

**Comment by claytonpbarrows** [comment]
- The original RTS-96 data didn't include warm start values. I have not developed that data for the update.
- We followed the RTS-96 template for heat rate information. As such, we didn't develop no-load heat inputs. However, it should be somewhat baked into the Net Heat Rate Pt 0.
