### ISSUE TITLE
PLEXOS Import is broken

### ISSUE THREAD

**Issue by claytonpbarrows** [GridMod/RTS-GMLC#62]
@jennielu92 
ed431a49438ee6e28f42e800327211a47e798fc3 is the last commit where the import process works

**Comment by jennielu92** [comment]
@claytonpbarrows it's working fine for me, are you using the correct commit of PSSE2PLEXOS?

**Comment by claytonpbarrows** [comment]
requires a cleaning of `outputs` before running the creation script
