### ISSUE TITLE
317_wind and 303_wind does not exist in PLEXOS solution

### ISSUE THREAD

**Issue by krishnakanaparthi** [GridMod/RTS-GMLC#63]
With reference to the RTS data, the time series data files for wind (DAY_AHEAD_wind.csv) includes wind profiles at 317_WIND_1	303_WIND_1.

However, the PLEXOS solution file (PLEXOS_DA_solution_generation.csv) which is published at the following location (RTS-GMLC/RTS_Data/FormattedData/PLEXOS/PLEXOS_Solution/) does not show the wind power outputs at these location.

Is this because wind at the these locations has been curtailed or is the data missing for the PLEXOS solution?

Thanks,
Krishna.

**Comment by oconnellm** [comment]
Those two generators are not turned on in PLEXOS. I think this was because the renewable penetration was too high so by default we only have two of the four turned on...?

So no data is missing

**Comment by claytonpbarrows** [comment]
OK, We need to reflect that difference in the dataset. Either we need to turn on all the included generators in the PLEXOS model, or we need to reflect the off status in the SourceData. I vote for the former.

**Comment by jennielu92** [comment]
We can do that - we were just seeing ridiculous amounts of curtailment, which was why we turned them off in the first place. Another option would be to turn on all the generators in the base case (and see where the curtailment is now, which could be different with all our changes), but still include the reduced RE penetration as a scenario.

**Comment by claytonpbarrows** [comment]
@bennettmcbrendan when you turn on the wind gens in the plexos model, can you commit a new .xml and close this?

**Comment by oconnellm** [comment]
This looks like it has been fixed. @bennettmcbrendan can you confirm that and close the issue if so?

**Comment by krishnakanaparthi** [comment]
@bennettmcbrendan, @claytonpbarrows.

Previously before June, the solution files that were provided had a total wind+solar (Utility+ Rooftop PV)  of 5231.4 GWh. This was obtained by multiplying the respective commitment solution (PLEXOS_DA_solution_commitment.csv) with the generation file (PLEXOS_DA_solution_generation.csv) only for the wind+solar units. The following was the overall data analysis.

Total load energy 37655.8 [GWh] - DA_hourly.csv
Area 1 load energy 12169.3 [GWh]
Area 1 available wind+solar energy 2624.0 [GWh]
Area 2 load energy 12188.7 [GWh]
Area 2 available wind+solar energy 323.5 [GWh]
Area 3 load energy 13297.9 [GWh]
Area 3 available wind+solar energy 2281.7 [GWh]

This 5231.4 GWh, I understood to be reduced RE penetration scenario which was mentioned in your earlier comments. This used to provide a feasible optimal solution in our set up. However, some hours (low load conditions) were producing non-feasible solution.

In the update during first week of June, the total load energy provided in the 'DAY_AHEAD_regional_Load.csv' reduced to 36689.6 [GWh] and subsequently the total wind+solar energy also dropped to 5113 [GWh] although RE penetration remained the same to around 14%.

However, in the current update of the solution files, it seems all the wind and solar units have been committed resulting in a total available wind+solar energy of 12110 [GWh]. This is inspite of the total load energy still being 36689.6 [GWh]. This might not result in a feasible solution at all for all the hours. Therefore, could you please have a look and let us know if the Unit Commitment information in the solution file could be used.

Also, new PV units seem to have been added (e..g 101_PV_1, 101_PV_2, 101_PV_3, 101_PV_4) increasing the total number of generating units to 158. In the earlier case, the total number of units were 125. Can this be looked into as well?

Thanks,
Krishna.
