### ISSUE TITLE
add R script to create the two PLEXOS solution csv files

### ISSUE THREAD

**Issue by claytonpbarrows** [GridMod/RTS-GMLC#66]
Can you please create/add a script to populate the csv files in [this](https://github.com/GridMod/RTS-GMLC/tree/master/RTS_Data/FormattedData/PLEXOS/PLEXOS_Solution/Model%20DAY_AHEAD%20Solution) folder?

**Comment by oconnellm** [comment]
added r scripts. Still need to test with a dummy db to make sure they work as planned.

**Comment by oconnellm** [comment]
And possibly move them or change filepointers within based on where final files will be located.
