### ISSUE TITLE
fix CT start time values

### ISSUE THREAD

**Issue by claytonpbarrows** [GridMod/RTS-GMLC#67]
CT cold start time is 0
CT hot start time is 0
CT warm start time is 1
How can this be?

**Comment by claytonpbarrows** [comment]
also add #35 to this script

**Comment by oconnellm** [comment]
Looks like the CT generator start times should be:
Cold - 1 hour
Warm - 0.75 hours
Hot - 0.25 hours

I don't think it would be a huge stretch to make warm 0.5 so its an even spread. But the original data has it at 0.75 hours.
