### ISSUE TITLE
Buses 13, 14, 15, 19, 20 mentioned in the RTS-GLMC model updates do not exist in original RTS-96 data (.m file)

### ISSUE THREAD

**Issue by krishnakanaparthi** [GridMod/RTS-GMLC#7]
In the link https://github.com/GridMod/RTS-GMLC/blob/master/RTS-GMLC_updates.md, it is mentioned that the RTS-GMLC model was obtained by making updates to the RTS-96 data that uses buses 13, 14, 15, 19, 20. However the buses in the .m file are numbered from 101 to 325. Could you please elaborate what these buses (13, 14, 15, 19, 20 etc.) are?

**Comment by kdheepak** [comment]
The RTS test system has three zones, distinguished by the hundredth digit in the zone number. 100, 200, and 300 represent the three zones. For example, Buses 13 should refer to 113, 213 and 313, copying @claytonpbarrows for confirmation.
