### ISSUE TITLE
sharp jumps in loadshapes

### ISSUE THREAD

**Issue by HimanshuJain17** [GridMod/RTS-GMLC#70]
@jennielu92 posting the issue about jumps in transmission loadshapes that we discussed over e-mail.

Attached are the load shapes for the peak week of July. In 5 of the 7 days of the week there are sharp jumps in the load shapes. Is this an error, or is there a reason behind these jumps?

![image](https://user-images.githubusercontent.com/26313500/27658814-8294a11c-5c0e-11e7-8f44-4b81b7791921.png)

[five minute load shapes.xlsx](https://github.com/GridMod/RTS-GMLC/files/1110131/five.minute.load.shapes.xlsx)

**Comment by claytonpbarrows** [comment]
@gbrinkman can you provide some insight to this? These are based on the WWSIS-2/LCGS load files labeled *BA_Promod_2020.csv*

**Comment by claytonpbarrows** [comment]
@HimanshuJain17, unfortunately I do not have a good explanation to this issue. We are aware that this data is unrealistic, but were unable to get better representations for the WWSIS study (from which this data was drawn).
