### ISSUE TITLE
fix peak RE output in load flow cases

### ISSUE THREAD

**Issue by claytonpbarrows** [GridMod/RTS-GMLC#78]
- [ ] find the period corresponding to peak load
- [ ] set Pmax to available capacity and Pout for RE generators
- [ ] generate the matpower file
- [ ] load into POWERWORLD
- [ ] save to PSSE

**Comment by bennettmcbrendan** [comment]
Day ahead peak load period
8/26 at 15:00
Real time peak load period
8/26 at 14:40

**Comment by claytonpbarrows** [comment]
cd02de8 should fix the issue of over-generation in the load flow cases, but still doesn't include RE generation
