### ISSUE TITLE
RTS_GMLC.m generators list

### ISSUE THREAD

**Issue by anyacastillo** [GridMod/RTS-GMLC#83]
The gen and gencost lists do not match in length

**Comment by claytonpbarrows** [comment]
@anyacastillo are you sure?
All of the structures  (mpc.gen, mpc.gencost, and mpc.gen_name) in the [MATPOWER file](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/FormattedData/MATPOWER/RTS_GMLC.m) have 158 entries...
Are you seeing something different?

**Comment by anyacastillo** [comment]
hi Clayton, sorry about that!  looks like I mucked around with the file, and then came back to it and forgot it was I.

I have some updated OPF results, will email you. Thanks!  (and sorry again for wasting your time)

**Comment by anyacastillo** [comment]
(btw the gen_status on the renewables is set to '0' so I incorrectly parsed them out)
