### ISSUE TITLE
Methods used to calculate the reserve requirements

### ISSUE THREAD

**Issue by maov-epri** [GridMod/RTS-GMLC#85]
Hi,

I understand that the spinning reserve requirements are 3% of the area load,  but it is not clear how the flexibility and regulation reserves requirements are estimated.  Could you please add some documentation detailing how are such reserve requirements computed? 

Thanks

**Comment by claytonpbarrows** [comment]
The methodology used to calculate the regulation and flexibiliity reserve requirements is documented [here](https://www.nrel.gov/docs/fy12osti/56169.pdf).
