### ISSUE TITLE
PowerModels parse broken 

### ISSUE THREAD

**Issue by jdlara-berkeley** [GridMod/RTS-GMLC#87]
@claytonpbarrows  Currently Power Models matpower parsing breaks with the latest version of the data. The error is related to the pwl cost functions.

**Comment by claytonpbarrows** [comment]
This is an issue with PowerModels. Specifically, the DC line adds a cost row that isn't compatible with the PWL cost format. 
I'm opening an issue in PowerModels

**Comment by claytonpbarrows** [comment]
The latest version of PowerModels fixes this issue

**Comment by ccoffrin** [comment]
To clarify the meaning of "latest", the fix is now in the master branch.  The next tagged version after v0.7.2 will include this fix.
