### ISSUE TITLE
RTS.m file when used in Matpower gives errors for the gen data when converting from external to internal indexing

### ISSUE THREAD

**Issue by krishnakanaparthi** [GridMod/RTS-GMLC#9]
When using the RTS-96 mat file (RTS.m) in Matpower, it needs conversion from external to internal indexing. This works correctly for the bus and branch data but not for the gen data.

**Comment by claytonpbarrows** [comment]
58929a1b58a6868300d473c375bb8b5f2ade7312 should address this, @krishnakanaparthi please let me know if you still have problems.
