### ISSUE TITLE
bus numbering in matpower format 

### ISSUE THREAD

**Issue by jd-lara** [GridMod/RTS-GMLC#90]
Matpower requires the buses to be numbered sequentially to enable some calculations. 

```Matlab 
PTDF = makePTDF(RTS_GMLC)
Error using makePTDF (line 70)
makePTDF: buses must be numbered consecutively in bus matrix; use ext2int() to convert to internal ordering
```

Using the Matpower provided function `ext2int()` eliminates branches and generates problems with the case. 

It would be better to store the buses in sequential ordering to avoid case transformations.

**Comment by ccoffrin** [comment]
Renaming the buses would be a massive departure from the original RTS specification.  I would recommend sticking with the standard bus numbers.  

It may also be useful to note that every real-world dataset I have encountered does not have purely sequential bus ids.

**Comment by ccoffrin** [comment]
To me this sounds like an issue for https://github.com/MATPOWER/matpower

**Comment by jd-lara** [comment]
@ccoffrin The RTS file I had had a mistake and it was fixed in the current version of the repo.
