### ISSUE TITLE
Missing script for PLEXOS database

### ISSUE THREAD

**Issue by pablogilu** [GridMod/RTS-GMLC#99]
Hello,

The script "run_PSSE2PLEXOS.R" is missing. It should be located in the 2-create-excel directory according to the README file, but is neither there nor in any other folder. So I am uncapable of creating the database.

Could you please provide the script?

Thank you,
Pablo

**Comment by claytonpbarrows** [comment]
This feature depends upon the [PIDG repo](https://github.com/nrel/pidg) to generate the plexos input files. It's included as a git submodule, so you'll need to run:
```
git submodule init
```

Also, I apologize for the (~2yr) delay in responding.
